apiVersion: apps/v1
kind: Deployment
metadata:
  annotations:
    tad.gitops.set/image: ".spec.template.spec.containers[0].image"
    tad.gitops.get/image: ".spec.template.spec.containers[0].image"
    tad.gitops.set/replicas: ".spec.replicas"
    tad.gitops.get/replicas: ".spec.replicas"
  name: backend-tests-go-qkssmpjg
spec:
  replicas: 1
  template:
    spec:
      containers:
        - image: quay.io/rhtap_qe/backend-tests-go-qkssmpjg:jenkins-c670f2de6c149c7963f885f2bd7f7585348ce7ed
          name: container-image
